BOSA21Q1-731 Gauges of votes per region should be visible even after deadline is reached
belighted/bosa pull request #211
Opened 2022-05-03 08:29 UTC by ThomasCollignon

[BOSA21Q1-731](https://belighted.atlassian.net/browse/BOSA21Q1-731)

To reproduce with prod DB:
- vote ongoing: /initiatives/i-658
- vote closed: /initiatives/i-653

2022-05-05 07:59 UTC, sergei-krylov requested changes
@ThomasCollignon , no you shouldn't change these methods as they're used in basic logic to determine if user can vote, etc.
Please make the change only in the corresponding view that displays the vote badges. Basic idea is that it just should ignore if initiative is closed or not.

2022-05-11 08:25 UTC, sergei-krylov commented on app/views/decidim/initiatives/initiatives/_progress_bar.html.erb
> +      <% if current_initiative.accepts_offline_votes? %>
In case the initiative type is configured for multiple scopes and to collect only offline votes (or mixed: online + offline votes) - offline votes will not be displayed in that case.
@ThomasCollignon is that intentional?

2022-05-11 13:11 UTC, ThomasCollignon commented on app/views/decidim/initiatives/initiatives/_progress_bar.html.erb
> +      <% if current_initiative.accepts_offline_votes? %>
I don't get your concern: I haven't changed that line.
If multiple scopes and only offline-votes, offline votes should be displayed, as before.

2022-05-12 05:56 UTC, ThomasCollignon commented
@sergei-krylov I get your point, I'll come back with another code.

2022-05-12 07:11 UTC, sergei-krylov approved these changes
Looks good!

2022-05-12 07:14 UTC, sergei-krylov commented on app/views/decidim/initiatives/initiatives/_progress_bar.html.erb
> +      <% if current_initiative.accepts_offline_votes? %>
Concern was that it should be shown for closed initiatives, and `accepts_offline_votes?` is checking if initiative is currently published, so offline votes won't be displayed in that case.

2022-05-12 07:14 UTC, merged