Migrate Sentry (BOSA21Q1-146)
belighted/bosa pull request #64
Opened 2021-05-21 07:45 UTC by MathieuGillard

## Description
- What?
- - Migrate to the new gem
- Why?
- - The old sentry-raven client has entered maintenance mode. If you're using sentry-raven, we recommend you to migrate to this new SDK.
- How?
- - Change the gemfile with the new library and add dependencies. Change application.rb with the new configuration and remove a job because he is managed by the library.
- Anything Else?
- - I was not able to test locally. So you have to test the code once deployed on staging.

## Ticket
[BOSA21Q1-146](https://belighted.atlassian.net/browse/BOSA21Q1-146?atlOrigin=eyJpIjoiZDU2NmY1N2U2ZWY1NDY3Mjg1Y2M4OGNkYTFlZGU4MjIiLCJwIjoiaiJ9)

## Type of changes

- [ ]  Docs changes
- [ ]  Refactoring
- [x]  Dependency upgrade
- [ ]  Bug fix
- [ ]  New feature
- [ ]  Breaking changes

2021-05-21 12:46 UTC, malbert requested changes

2021-05-21 12:46 UTC, malbert commented on Gemfile
> +gem 'delayed_job', '~> 4.1', '>= 4.1.9'
@MathieuGillard We don't have  delayed_job. we have Sidekiq.
I think it is a wrong copy paste.

We can remove the 2 lines:
gem "sentry-delayed_job"
gem 'delayed_job', '~> 4.1', '>= 4.1.9'

@sergei-krylov   Do you confirm?

2021-05-21 12:48 UTC, sergei-krylov commented on Gemfile
> +gem 'delayed_job', '~> 4.1', '>= 4.1.9'
Yes, we can remove it.

2021-05-21 13:00 UTC, sergei-krylov commented on Gemfile
> +gem 'delayed_job', '~> 4.1', '>= 4.1.9'
Also, it is missing the changes in Gemfile.lock

2021-05-21 14:47 UTC, malbert approved these changes

2021-05-25 05:54 UTC, sergei-krylov approved these changes

2021-05-25 06:05 UTC, merged